package com.lt.base.outrest.common;

import org.springframework.security.core.userdetails.UserDetails;

import com.lt.base.service.JwtTokenService;

public class TestMain {

	public static void main(String[] args) {
		JwtTokenService service = new JwtTokenService();
		String string = "eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJsdCIsImF1ZCI6IlUyMDE4MDYyMTEyNTMwMjgxNSIsImV4cCI6MTUzOTU5ODI4NywianRpIjoiVTIwMTgwNjIxMTI1MzAyODE1IiwiaWF0IjoxNTM5NTk2NDg3LCJuYmYiOjE1Mzk1OTY0ODYsInN1YiI6IlUyMDE4MDYyMTEyNTMwMjgxNSIsInVzZXIiOiJ7XCJhY2NvdW50Tm9uRXhwaXJlZFwiOnRydWUsXCJhY2NvdW50Tm9uTG9ja2VkXCI6dHJ1ZSxcImF1dGhvcml0aWVzXCI6W3tcImF1dGhvcml0eVwiOlwiUk9MRV9JTkNSRUFTX0VST0xFXCJ9LHtcImF1dGhvcml0eVwiOlwiUk9MRV9SRU1PVkVfUkVTT1VSQ0VcIn0se1wiYXV0aG9yaXR5XCI6XCJST0xFX1VTRVJfTElTVFwifSx7XCJhdXRob3JpdHlcIjpcIlJPTEVfU0hPV1wifSx7XCJhdXRob3JpdHlcIjpcIlJPTEVfTElTVF9ST0xFXCJ9LHtcImF1dGhvcml0eVwiOlwiUk9MRV9BTExfUkVTT1VSQ0VcIn0se1wiYXV0aG9yaXR5XCI6XCJST0xFX0FERF9VU0VSXCJ9LHtcImF1dGhvcml0eVwiOlwiUk9MRV9SRU1PVkVfUk9MRVwifSx7XCJhdXRob3JpdHlcIjpcIlJPTEVfSU5DUkVBU0VfUkVTT1VSQ0VcIn0se1wiYXV0aG9yaXR5XCI6XCJST0xFX0FMTF9UUkVFX1JFU09VUkNFXCJ9LHtcImF1dGhvcml0eVwiOlwiUk9MRV9BRE1JTlwifSx7XCJhdXRob3JpdHlcIjpcIlJPTEVfTE9HT1VUXCJ9LHtcImF1dGhvcml0eVwiOlwiUk9MRV9DRU5URVJcIn1dLFwiY29pXCI6XCIxMjMxMjMxMjMxMjMxXCIsXCJjcmVkZW50aWFsc05vbkV4cGlyZWRcIjp0cnVlLFwiZW5hYmxlZFwiOnRydWUsXCJpZFwiOlwiOGEwODM2ODA2NDIwYjAzMjAxNjQyMGIwNGVlZjAwMDBcIixcIm5hbWVcIjpcIuadjuWbm1wiLFwidGVsZVwiOlwiMTExMTExMTExMTFcIixcInR5cGVcIjpcIjFcIixcInVzZXJDb2RlXCI6XCJVMjAxODA2MjExMjUzMDI4MTVcIixcInVzZXJuYW1lXCI6XCJVMjAxODA2MjExMjUzMDI4MTVcIn0ifQ.cXNQoy1qZJSBPuwTsVJL7Cdsa841royCliAfGbgKsaW5x68R0pvlZK_yo29I0-GVM_IJikaQq_wyw8xSC9x_7w";
		UserDetails details = service.getUserFromToken(string);
		System.out.println(details.getPassword());
	}

}
